import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Providers from "./providers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Providers>
      <Header />
          <Link href={"/"} className="bold mx-5  text-lg">Home</Link>
          <Link href={"/cart"} className="bold text-lg">Cart</Link>
        {children}
        <Footer />
        </Providers>
        
      
        </body>
    </html>
  );
}
